[metadata]
name = deployment-scripts
version = 1.5.2606 (os-dev - 8ccb02 [2026-06-19 19:21:05])
author = AnyLog Co.
contact = info@anylog.co
description = Deployment Scripts for Anylog nodes
license = Copyright AnyLog Co.
site = https://anylog.co
docs = https://github.com/AnyLog-co/documentation
source = https://github.com/AnyLog-co