[metadata]
name = deployment-scripts
version = 2.0.2606 (os-dev - af15d3 [2026-08-27 17:40:50])
author = AnyLog Co.
contact = info@anylog.co
description = Deployment Scripts for Anylog nodes
license = Copyright AnyLog Co.
site = https://anylog.co
docs = https://github.com/AnyLog-co/documentation
source = https://github.com/AnyLog-co