[metadata]
name = deployment-scripts
version = 1.4.2604 (os-dev - 79fe95 [2026-06-12 03:33:15])
author = AnyLog Co.
contact = info@anylog.co
description = Deployment Scripts for Anylog nodes
license = Copyright AnyLog Co.
site = https://anylog.co
docs = https://github.com/AnyLog-co/documentation
source = https://github.com/AnyLog-co