{
 "title": "Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "wp_analog_aggregate",
   "type": "table",
   "gridPos": { "h": 1, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "payload": "{\n  \"type\": \"increments\",\n  \"sql\" : \"select increments(insert_timestamp), max(insert_timestamp) as insert_timestamp, avg(combinedturbidityai_pv) as combinedturbidityai_pv, avg(filter1turbidityai_pv) as filter1turbidityai_pv, avg(filter2turbidityai_pv) as filter2turbidityai_pv, avg(filter3turbidityai_pv) as filter3turbidityai_pv, max(phai_pv) as phai_pv, avg(combinedchlorinatorai_pv) as combinedchlorinatorai_pv, avg(freechlorinatorai_pv) as freechlorinatorai_pv, avg(rawwatermeterai_pv) as rawwatermeterai_pv, avg(carbonfeeder_speedai_pv) as carbonfeeder_speedai_pv, avg(watertowerlevelai_pv) as watertowerlevelai_pv, avg(rawwatermetertotalizer_curday) as rawwatermetertotalizer_curday, avg(rawwatermetertotalizer_yesday) as rawwatermetertotalizer_yesday FROM wp_analog\",\n  \"grafana\": {\n    \"format_as\": \"timeseries\",\n    \"data_points\" : \"fixed\"\n  },\n  \"interval\": \"dashboard\"\n}\n",
     "target": "cos.wp_analog"
    }
   ]
  },
  {
   "title": "wp_analog_source",
   "type": "table",
   "gridPos": { "h": 1, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "payload": "{\n  \"sql\": \"SELECT insert_timestamp, chemicalscale1ai_pv, chemicalscale2ai_pv, chemicalscale3ai_pv, chemicalscale4ai_pv FROM wp_analog ORDER BY insert_timestamp DESC\"\n}",
     "target": "cos.wp_analog"
    }
   ]
  },
  {
   "title": "wp_digital",
   "type": "table",
   "gridPos": { "h": 1, "w": 3, "x": 6, "y": 0 },
   "targets": [
    {
     "payload": "{\n  \"sql\" : \"SELECT insert_timestamp, atsnormalrdydi, atsonstandbydi, atsstandybyrdydi, clearwellhighleveldi, clearwelllowleveldi, generatoralarmdi, generatorstatusdi, oxygenmonitordi, plantrunningdi, plantstartdi, servicepump1running_di, servicepump2running_di, plantshutdowndo, watertowerlevelcommsdi, plantenablechemicalsdo, combinedchlorinatorvacdi, freechlorinatorvacdi, carbonfeeder_runningfwd FROM wp_digital\"\n}\n",
     "target": "cos.wp_digital"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<p class =\"panel-title-text\"\n  style=\"\n    font-size: xx-large;\n    text-align:center;\n    height:40%;\n    bottom:0;\n    margin:0;\">Water Plant</p>\n<hr\n  style=\"\n    width:40%;\n    margin-bottom: 8px;\">\n<p class =\"panel-subtitle-text\"\n  style=\"\n    font-size: large;\n    text-align:center;\n    height:60%;\n    bottom:0;\n    margin:0;\n    max-width: 100%;\">Overview</p>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Power Status",
   "type": "canvas",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 4 },
   "targets": [
    { "panelId": 28 }
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 4 },
   "targets": [
    { "panelId": 28 }
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 4 },
   "targets": [
    { "panelId": 28 }
   ]
  },
  {
   "title": "Carbon Feeder",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 2, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "panelId": 27 }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "masslb" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 29 }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 11, "y": 9 },
   "targets": [
    { "panelId": 28 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 13 },
   "options": {
    "content": "<p class =\"panel-title-text\"\n  style=\"\n    font-size: large;\n    text-align:center;\n    height:60%;\n    bottom:0;\n    margin:0;\n    max-width: 100%;\">Clear Well</P>\n<p class = \"panel-subtitle-text\"\n  style=\"\n    text-align:center;\n    height:40%;\n    bottom:0;\n    margin:0;\n    max-width: 100%;\">Level</P>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 13 },
   "options": {
    "content": "<p class =\"panel-title-text\"\n  style=\"\n    font-size: large;\n    text-align:center;\n    height:60%;\n    bottom:0;\n    margin:0;\n    max-width: 100%;\">Water Tower</P>\n<p class = \"panel-subtitle-text\"\n  style=\"\n    text-align:center;\n    height:40%;\n    bottom:0;\n    margin:0;\n    max-width: 100%;\">Level</P>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 4, "y": 13 },
   "options": {
    "content": "<p class =\"panel-title-text\"\n  style=\"\n    font-size: large;\n    text-align:center;\n    height:60%;\n    bottom:0;\n    margin:0;\n    max-width: 100%;\">Raw Water</P>\n<p class = \"panel-subtitle-text\"\n  style=\"\n    text-align:center;\n    height:40%;\n    bottom:0;\n    margin:0;\n    max-width: 100%;\">Flow, Totals</P>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 13 },
   "options": {
    "content": "<p class =\"panel-title-text\"\n  style=\"\n    font-size: large;\n    text-align:center;\n    height:60%;\n    bottom:0;\n    margin:0;\n    max-width: 100%;\">Water Quality</P>\n<p class = \"panel-subtitle-text\"\n  style=\"\n    text-align:center;\n    height:40%;\n    bottom:0;\n    margin:0;\n    max-width: 100%;\">pH, Turbidity, Chlorine</P>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 15 },
   "targets": [
    {
     "payload": "{\r\n  \"sql\": \"SELECT insert_timestamp, clearwellhighleveldi, clearwelllowleveldi FROM wp_digital ORDER BY insert_timestamp DSC limit 1\",\r\n  \"time_range\": false,\r\n  \"timezone\": \"local\"\r\n}",
     "query": "low_level = from(bucket: \"csobsidian's Bucket\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"clearWell\")\r\n    |> filter(fn: (r) => r._field == \"LowLevel\")\r\n    |> last()\r\n    //|> map(fn: (r) => ({ r with _value: r._value + 1.0}))\r\n    //|> yield(name: \"low_level\")\r\n\r\nhigh_level = from(bucket: \"csobsidian's Bucket\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"clearWell\")\r\n    |> filter(fn: (r) => r._field == \"HighLevel\")\r\n    |> last()\r\n    //|> map(fn: (r) => ({ r with _value: (r._value + 1.0) * 2.0}))\r\n    //|> yield(name: \"high_level\")\r\n\r\n//join(tables: {t1: low_level, t2: high_level}, on: [\"_time\"])\r\nunion(tables: [low_level, high_level])\r\n    |> drop(columns: [\"_measurement\", \"_field\"])\r\n    |> sum()\r\n",
     "target": "cos.wp_digital"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 1, "x": 2, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "payload": "{\r\n  \"sql\": \"SELECT insert_timestamp, watertowerlevelai_pv, FROM wp_analog ORDER BY insert_timestamp DESC limit 1\",\r\n  \"time_range\": false,\r\n  \"timezone\": \"local\"\r\n}",
     "query": "from(bucket: \"csobsidian's Bucket\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"watertower\")\r\n    |> filter(fn: (r) => r._field == \"Level\")\r\n    |> last()\r\n\r\n    //|> map(fn: (r) => ({r with _value: r._value * 0.001}))\r\n",
     "target": "cos.wp_analog"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 1, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "payload": "{\r\n  \"sql\": \"SELECT insert_timestamp, watertowerlevelai_pv::function(([scaled] - 110.0) / (135.0 - 110.0) * (100.0 - 0.0) + 0.0) as scaled, FROM wp_analog ORDER BY insert_timestamp DESC limit 1\",\r\n  \"time_range\": false,\r\n  \"timezone\": \"local\"\r\n}",
     "query": "from(bucket: \"csobsidian's Bucket\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"watertower\")\r\n    |> filter(fn: (r) => r._field == \"Level\")\r\n    |> last()\r\n\r\n    //|> map(fn: (r) => ({r with _value: r._value * 0.001}))\r\n",
     "target": "cos.wp_analog"
    }
   ]
  },
  {
   "title": "Raw Water Flow",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 5, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "flowgpm" } },
   "targets": [
    {
     "payload": "{\r\n  \"type\": \"increments\",\r\n  \"time_column\": \"insert_timestamp\",\r\n  \"value_column\": \"rawwatermeterai_pv\",\r\n  \"functions\": [\"avg\"],\r\n  \"grafana\": {\r\n    \"format_as\": \"timeseries\"\r\n  },\r\n  \"interval\": \"dashboard\",\r\n  \"timezone\": \"local\"\r\n}",
     "query": "from(bucket: \"csobsidian's Bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"waterMeter\")\r\n  |> filter(fn: (r) => r.sensor_id == \"Raw\")\r\n  |> filter(fn: (r) => r._field == \"Flow\")\r\n  \r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)",
     "target": "cos.wp_analog"
    }
   ]
  },
  {
   "title": "Raw Water Flow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "flowgpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "payload": "{\r\n  \"type\": \"increments\",\r\n  \"time_column\": \"insert_timestamp\",\r\n  \"value_column\": \"rawwatermeterai_pv\",\r\n  \"functions\": [\"avg\"],\r\n  \"grafana\": {\r\n    \"format_as\": \"timeseries\"\r\n  },\r\n  \"timezone\": \"local\"\r\n}",
     "query": "from(bucket: \"csobsidian's Bucket\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"waterMeter\")\r\n    |> filter(fn: (r) => r.sensor_id == \"Raw\")\r\n    |> filter(fn: (r) => r._field == \"Flow\")\r\n    |> last()\r\n\r\n    //|> map(fn: (r) => ({r with _value: r._value * 0.001}))\r\n",
     "target": "cos.wp_analog"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 4, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "pH" } },
   "targets": [
    {
     "payload": "{\r\n  \"type\": \"increments\",\r\n  \"time_column\": \"insert_timestamp\",\r\n  \"value_column\": \"phai_pv\",\r\n  \"functions\": [\"avg\"],\r\n  \"grafana\": {\r\n    \"format_as\": \"timeseries\"\r\n  },\r\n  \"interval\": \"dashboard\",\r\n  \"timezone\": \"local\"\r\n}",
     "query": "from(bucket: \"csobsidian's Bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"ph\")\r\n  |> drop(columns: [\"sensor_id\"])\r\n  |> drop(columns: [\"location\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)",
     "target": "cos.wp_analog"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "NTU" } },
   "targets": [
    {
     "payload": "{\r\n  \"type\": \"increments\",\r\n  \"time_column\": \"insert_timestamp\",\r\n  \"value_column\": \"combinedturbidityai_pv\",\r\n  \"functions\": [\"avg\"],\r\n  \"grafana\": {\r\n    \"format_as\": \"timeseries\"\r\n  },\r\n  \"interval\": \"dashboard\",\r\n  \"timezone\": \"local\"\r\n}",
     "query": "from(bucket: \"csobsidian's Bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"turbidity\")\r\n  |> drop(columns: [\"location\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)",
     "target": "cos.wp_analog"
    },
    {
     "payload": "{\r\n  \"type\": \"increments\",\r\n  \"time_column\": \"insert_timestamp\",\r\n  \"value_column\": \"filter1turbidityai_pv\",\r\n  \"functions\": [\"avg\"],\r\n  \"grafana\": {\r\n    \"format_as\": \"timeseries\"\r\n  },\r\n  \"interval\": \"dashboard\",\r\n  \"timezone\": \"local\"\r\n}",
     "target": "cos.wp_analog"
    },
    {
     "payload": "{\r\n  \"type\": \"increments\",\r\n  \"time_column\": \"insert_timestamp\",\r\n  \"value_column\": \"filter2turbidityai_pv\",\r\n  \"functions\": [\"avg\"],\r\n  \"grafana\": {\r\n    \"format_as\": \"timeseries\"\r\n  },\r\n  \"interval\": \"dashboard\",\r\n  \"timezone\": \"local\"\r\n}",
     "target": "cos.wp_analog"
    },
    {
     "payload": "{\r\n  \"type\": \"increments\",\r\n  \"time_column\": \"insert_timestamp\",\r\n  \"value_column\": \"filter3turbidityai_pv\",\r\n  \"functions\": [\"avg\"],\r\n  \"grafana\": {\r\n    \"format_as\": \"timeseries\"\r\n  },\r\n  \"interval\": \"dashboard\",\r\n  \"timezone\": \"local\"\r\n}",
     "target": "cos.wp_analog"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "payload": "{\r\n  \"type\": \"increments\",\r\n  \"sql\" : \"SELECT increments(insert_timestamp), max(insert_timestamp) as timestamp, avg(combinedchlorinatorai_pv), avg(freechlorinatorai_pv) from wp_analog\",\r\n  \"grafana\": {\r\n    \"format_as\": \"timeseries\"\r\n  },\r\n  \"interval\": \"dashboard\",\r\n  \"trace_level\" : 1\r\n}",
     "query": "from(bucket: \"csobsidian's Bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"turbidity\")\r\n  |> drop(columns: [\"location\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)",
     "target": "cos.wp_analog"
    }
   ]
  },
  {
   "title": "Total Water - Today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Kgal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "payload": "{\r\n  \"type\": \"increments\",\r\n  \"time_column\": \"insert_timestamp\",\r\n  \"value_column\": \"rawwatermetertotalizer_curday\",\r\n  \"functions\": [\"avg\"],\r\n  \"grafana\": {\r\n    \"format_as\": \"timeseries\"\r\n  },\r\n  \"timezone\": \"local\"\r\n}",
     "query": "from(bucket: \"csobsidian's Bucket\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"waterMeter\")\r\n    |> filter(fn: (r) => r.sensor_id == \"Raw\")\r\n    |> filter(fn: (r) => r._field == \"TotalToday\")\r\n    |> last()\r\n    |> map(fn: (r) => ({r with _value: r._value * 0.001}))",
     "target": "cos.wp_analog"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "targets": [
    {
     "payload": "{\r\n  \"type\": \"increments\",\r\n  \"time_column\": \"insert_timestamp\",\r\n  \"value_column\": \"watertowerlevelai_pv\",\r\n  \"functions\": [\"avg\"],\r\n  \"grafana\": {\r\n    \"format_as\": \"timeseries\"\r\n  },\r\n  \"interval\": \"dashboard\",\r\n  \"timezone\": \"local\"\r\n}",
     "query": "from(bucket: \"csobsidian's Bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"waterMeter\")\r\n  |> filter(fn: (r) => r.sensor_id == \"Raw\")\r\n  |> filter(fn: (r) => r._field == \"Flow\")\r\n  \r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)",
     "target": "cos.wp_analog"
    }
   ]
  },
  {
   "title": "Total Water - Yesterday",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Kgal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "payload": "{\r\n  \"type\": \"increments\",\r\n  \"time_column\": \"insert_timestamp\",\r\n  \"value_column\": \"rawwatermetertotalizer_yesday\",\r\n  \"functions\": [\"avg\"],\r\n  \"grafana\": {\r\n    \"format_as\": \"timeseries\"\r\n  },\r\n  \"timezone\": \"local\"\r\n}",
     "query": "from(bucket: \"csobsidian's Bucket\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"waterMeter\")\r\n    |> filter(fn: (r) => r.sensor_id == \"Raw\")\r\n    |> filter(fn: (r) => r._field == \"TotalToday\")\r\n    |> last()\r\n    |> map(fn: (r) => ({r with _value: r._value * 0.001}))",
     "target": "cos.wp_analog"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 26 },
   "targets": [
    {
     "payload": "{\r\n  \"sql\": \"SELECT insert_timestamp, watertowerlevelcommsdi FROM wp_digital ORDER BY insert_timestamp DSC limit 1\",\r\n  \"time_range\": false,\r\n  \"timezone\": \"local\"\r\n}",
     "query": "low_level = from(bucket: \"csobsidian's Bucket\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"clearWell\")\r\n    |> filter(fn: (r) => r._field == \"LowLevel\")\r\n    |> last()\r\n    //|> map(fn: (r) => ({ r with _value: r._value + 1.0}))\r\n    //|> yield(name: \"low_level\")\r\n\r\nhigh_level = from(bucket: \"csobsidian's Bucket\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r._measurement == \"clearWell\")\r\n    |> filter(fn: (r) => r._field == \"HighLevel\")\r\n    |> last()\r\n    //|> map(fn: (r) => ({ r with _value: (r._value + 1.0) * 2.0}))\r\n    //|> yield(name: \"high_level\")\r\n\r\n//join(tables: {t1: low_level, t2: high_level}, on: [\"_time\"])\r\nunion(tables: [low_level, high_level])\r\n    |> drop(columns: [\"_measurement\", \"_field\"])\r\n    |> sum()\r\n",
     "target": "cos.wp_digital"
    }
   ]
  }
 ]
}